-- QuantEdge Snowflake Schema Setup
-- Run this once to initialize the data warehouse

-- Create database and schema
CREATE DATABASE IF NOT EXISTS QUANTEDGE;
USE DATABASE QUANTEDGE;
CREATE SCHEMA IF NOT EXISTS FACTORS;
USE SCHEMA FACTORS;

-- Raw price data
CREATE TABLE IF NOT EXISTS PRICES_RAW (
    DATE DATE NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
    OPEN FLOAT,
    HIGH FLOAT,
    LOW FLOAT,
    CLOSE FLOAT,
    VOLUME BIGINT,
    LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DATE, TICKER)
);

-- Raw fundamentals
CREATE TABLE IF NOT EXISTS FUNDAMENTALS_RAW (
    TICKER VARCHAR(10) NOT NULL,
    MARKET_CAP FLOAT,
    PE_RATIO FLOAT,
    PB_RATIO FLOAT,
    PS_RATIO FLOAT,
    ROE FLOAT,
    ROA FLOAT,
    DEBT_TO_EQUITY FLOAT,
    CURRENT_RATIO FLOAT,
    REVENUE_GROWTH FLOAT,
    EARNINGS_GROWTH FLOAT,
    GROSS_MARGINS FLOAT,
    OPERATING_MARGINS FLOAT,
    SECTOR VARCHAR(50),
    INDUSTRY VARCHAR(100),
    FETCHED_AT TIMESTAMP,
    LOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TICKER)
);

-- Computed factor scores
CREATE TABLE IF NOT EXISTS FACTOR_SCORES (
    AS_OF_DATE DATE NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
    VALUE_SCORE FLOAT,
    MOMENTUM_SCORE FLOAT,
    QUALITY_SCORE FLOAT,
    COMPOSITE_SCORE FLOAT,
    REGIME INTEGER,
    REGIME_LABEL VARCHAR(10),
    COMPUTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (AS_OF_DATE, TICKER)
);

-- Backtest results
CREATE TABLE IF NOT EXISTS BACKTEST_RESULTS (
    RUN_ID VARCHAR(50) NOT NULL,
    STRATEGY VARCHAR(50) NOT NULL,
    AS_OF_DATE DATE,
    SHARPE_RATIO FLOAT,
    ANNUALIZED_RETURN FLOAT,
    MAX_DRAWDOWN FLOAT,
    CALMAR_RATIO FLOAT,
    MEAN_IC FLOAT,
    N_PERIODS INTEGER,
    COMPUTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RUN_ID, STRATEGY)
);

-- A/B test results
CREATE TABLE IF NOT EXISTS AB_TEST_RESULTS (
    TEST_DATE DATE NOT NULL,
    TREATMENT VARCHAR(50),
    CONTROL VARCHAR(50),
    T_STAT FLOAT,
    P_VALUE FLOAT,
    COHENS_D FLOAT,
    SIGNIFICANT BOOLEAN,
    DIRECTION VARCHAR(30),
    ADEQUATELY_POWERED BOOLEAN,
    MIN_N_REQUIRED INTEGER,
    N_TREATMENT INTEGER,
    N_CONTROL INTEGER,
    COMPUTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TEST_DATE, TREATMENT, CONTROL)
);

-- Information coefficient history
CREATE TABLE IF NOT EXISTS IC_HISTORY (
    DATE DATE NOT NULL,
    FACTOR VARCHAR(30) NOT NULL,
    REGIME INTEGER,
    REGIME_LABEL VARCHAR(10),
    IC FLOAT,
    T_STAT FLOAT,
    P_VALUE FLOAT,
    N_OBSERVATIONS INTEGER,
    COMPUTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DATE, FACTOR)
);

-- Grant access
GRANT USAGE ON DATABASE QUANTEDGE TO ROLE SYSADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA FACTORS TO ROLE SYSADMIN;
